#1. DTM 준비

In [2]:
import pandas as pd
df = pd.read_csv("news.csv")
df["articles"]

0      게티이미지뱅크 콩나물(사진)은 대두를 발아시켜 뿌리를 자라게 한 것이다. 동의보감에...
1      사진 한 장 없이 떠난 일지 스님 불교 현실에 대한 질타 등 생전에 연재했던 글, ...
2      이재익의 아재음악 열전전태관(왼쪽)과 김종진. <한겨레> 자료사진 2018년을 얼마...
3      서울대병원 제공서울대병원은 올해 1월부터 국내에서 독자적으로 개발한 인공지능 기술을...
4      ㆍ2.1㎓ 속도 ‘엑시노스 오토 V9’ㆍ2021년 생산 차량부터 탑재2021년 생산...
                             ...                        
395    박정호 SK텔레콤 사장이 SK브로드밴드 사장을 겸직한 이후 첫 행보로 ‘옥수수 연합...
396    LG전자가 세계 최초 88인치 8K OLED TV를 내놓는다. 인공지능(AI) 기술...
397    게임은 사회악 아닌 건전한 놀이문화(지디넷코리아=이도원 기자)"게임산업 전체의 발전...
398    10여년 만에 매출예상치 하향…주가도 폭락(지디넷코리아=김익현 기자)최근 10년 여...
399    [머니투데이 판교(경기)=김지영 기자] [최대주주 지분 매각설에 '긴장감' 흘러…게...
Name: articles, Length: 400, dtype: object

In [3]:
print( df['label'].value_counts( ) )  #label 컬럼의 범주별 빈도
print( df.info() )

label
0    200
1    200
Name: count, dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Unnamed: 0  400 non-null    int64 
 1   label       400 non-null    int64 
 2   articles    400 non-null    object
dtypes: int64(2), object(1)
memory usage: 9.5+ KB
None


In [4]:
!pip install konlpy

from konlpy.tag import Okt
okt = Okt() #Kkma, Hannanum....
okt.nouns( df["articles"][0] )  #수집된 첫번째 기사에 대한 명사

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.4/19.4 MB 49.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 488.6/488.6 kB 40.5 MB/s eta 0:00:00


['게티',
 '이미지',
 '뱅크',
 '콩나물',
 '사진',
 '은',
 '대두',
 '발아',
 '뿌리',
 '것',
 '동의보감',
 '콩나물',
 '온',
 '몸',
 '근육',
 '뼈',
 '때',
 '도움',
 '제반',
 '염증',
 '억제',
 '효과',
 '콩나물',
 '식물',
 '단백질',
 '아스파라긴산',
 '은',
 '프랑',
 '과학자',
 '아스파라거스',
 '발견',
 '이름',
 '아스파라긴산',
 '암모니아',
 '대사',
 '촉진',
 '독소',
 '흡수',
 '혈액',
 '통해',
 '제거',
 '간',
 '건강',
 '도움',
 '이',
 '때문',
 '숙취',
 '해소',
 '효과',
 '또',
 '콩팥',
 '기능',
 '요산',
 '배설',
 '촉진',
 '시킴',
 '동시',
 '신경통',
 '류머티즘',
 '효과',
 '콩나물',
 '대두',
 '상태',
 '일',
 '때',
 '비타민',
 '발아',
 '과정',
 '합성',
 '비타민',
 '비타민',
 '피부',
 '면역',
 '콩나물',
 '조리',
 '과정',
 '비타민',
 '파괴',
 '때문',
 '조리',
 '섭취',
 '게',
 '정명',
 '진',
 '의학',
 '전문',
 '기자',
 '정명',
 '진',
 '기자',
 '세상',
 '모든',
 '골',
 '이야기',
 '파스',
 '보이',
 '연예',
 '뉴스',
 '스타',
 '저작권',
 '파이낸셜뉴스',
 '무단',
 '재',
 '재',
 '배포',
 '금지']

In [5]:
def token(text):  #함수를 만드는 부분
    tokens_ko = okt.nouns(text) #nouns를 morphs로 바꾸면 명사외에도...
    return tokens_ko

In [6]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

tf_vect = TfidfVectorizer(tokenizer=token,
                          #stop_words 단어를 제거
                          stop_words=['건','악','최', '초','총','탈', '폭'],
                          #단어들이 최소 전체의 10% 문서에서 나오는 것만 DTM에 사용
                          min_df=0.1)
dtm = tf_vect.fit_transform( df.articles )
dtm

/usr/local/lib/python3.10/dist-packages/sklearn/feature_extraction/text.py:528: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


<400x364 sparse matrix of type '<class 'numpy.float64'>'
	with 29578 stored elements in Compressed Sparse Row format>

In [7]:
tf_vect.vocabulary_
tf_vect.get_feature_names_out()

array(['가격', '가능성', '가운데', '가장', '가지', '가치', '각각', '간', '감소', '강조', '개',
       '개발', '개선', '개인', '거나', '건강', '것', '게', '게임', '결과', '결정', '경우',
       '경쟁', '경쟁력', '경제', '경험', '계속', '계획', '고', '고려', '곳', '공간', '공개',
       '과', '과거', '과정', '관계', '관계자', '관련', '관리', '관심', '관측', '교수', '구독',
       '국가', '국내', '국제', '규모', '규제', '그', '그동안', '글로벌', '금지', '기간', '기능',
       '기도', '기록', '기반', '기사', '기술', '기업', '기자', '기존', '기준', '길', '김',
       '나', '날', '내', '내용', '네이버', '년', '누구', '눈', '뉴스', '다른', '다만', '다시',
       '다음', '단계', '달', '당시', '대부분', '대비', '대상', '대표', '대한', '대해', '더',
       '더욱', '데', '데이터', '도', '도움', '동시', '동안', '동영상', '두', '뒤', '등',
       '등장', '때', '때문', '또', '또한', '뜻', '라며', '로', '를', '마련', '마지막', '만',
       '만큼', '만화', '말', '매우', '매출', '먼저', '메인', '며', '면서', '명', '명의',
       '모델', '모두', '모든', '모바일', '모습', '목표', '못', '무단', '무엇', '문제', '문화',
       '미국', '미디어', '미래', '및', '바', '바로', '바로가기', '반응', '발생', '발표', '방법',
       '방송', '방식', '배', '배경', '배포', '번', '법인', '변화', '병원',

In [8]:
df2 = pd.DataFrame(dtm.todense(),
                   columns = tf_vect.get_feature_names_out())

- 데이터 파티셔닝

In [9]:
from sklearn.model_selection import train_test_split

train_df, test_df = train_test_split( df, test_size=0.2)

In [10]:
train_df.shape

(320, 3)

- Tfidf로 DTM 만들기

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np
tfidf_vect = CountVectorizer(tokenizer=token, min_df=10)
tfidf_vect.fit(train_df['articles'])  #train의 명사를 뽑은 것까지

/usr/local/lib/python3.10/dist-packages/sklearn/feature_extraction/text.py:528: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


CountVectorizer(min_df=10, tokenizer=<function token at 0x784df30ceef0>)

In [12]:
tfidf_matrix_train = tfidf_vect.transform(train_df['articles'])
tfidf_matrix_test = tfidf_vect.transform(test_df['articles'])

In [13]:
tfidf_vect.vocabulary_.keys()

dict_keys(['기자', '면역', '의', '임', '결과', '기대', '올해', '초', '미국', '식품', '지속', '치료', '제', '허가', '신청', '대표', '사진', '개발', '혁신', '것', '라며', '말', '위해', '수요', '파악', '여러', '대상', '동시', '진행', '전략', '그', '중심', '자회사', '과', '공동', '중인', '수', '사업', '가능성', '가장', '후보', '물질', '로', '꼽', '게', '기술', '하이브리드', '신호', '전달', '융합', '약물', '활', '높이', '여기', '공격', '핵심', '역할', '증가', '접목', '설명', '은', '몸', '안', '를', '이', '회사', '제조', '데', '안정', '확보', '프랑스', '기업', '시도', '계획', '잘못', '생산', '능력', '공급', '고', '용', '기간', '며', '점', '기존', '키', '등', '대부분', '자기', '제거', '암', '라면', '현재', '지난해', '자주', '비교', '언급', '다른', '무엇', '시간', '결합', '활용', '효과', '매우', '전망', '국내', '환자', '단독', '대해', '논의', '피부', '티', '대한', '후', '평균', '생존', '개월', '종', '한국', '최초', '시행', '중간', '작년', '수술', '및', '표준', '경우', '시작', '외', '앞', '집중', '강조', '부분', '사용', '적용', '주', '월', '매일', '번', '편의', '획기', '시장', '규모', '연간', '수준', '독일', '개', '국가', '예정', '만', '비용', '때문', '일단', '다음', '추진', '모색', '사례', '성공', '유럽', '뒤', '단계', '일부', '근육', '반응', '병', '설계', '자체', '가지', '질환', '역량', '보유', 

#2. 텍스트와 군집 분석

In [14]:
tfidf_matrix_train

<320x1432 sparse matrix of type '<class 'numpy.int64'>'
	with 41513 stored elements in Compressed Sparse Row format>

In [17]:
from sklearn.metrics.pairwise import cosine_similarity, cosine_distances
print(cosine_similarity(tfidf_matrix_train[30,:] , tfidf_matrix_train[100,:])) # 행에 대한 31번째 인덱싱, 뒤에는 슬라이싱 101번째
print(train_df.iloc[30,2])
print(train_df.iloc[100,2])

print(cosine_similarity(tfidf_matrix_train[30,:] , tfidf_matrix_train[30,:]))
cosine_similarity(tfidf_matrix_train)
cosine_distances(tfidf_matrix_train)

[[0.14384416]]
미세먼지를 피해 시민들이 마스크를 끼고 지나가고 있다/사진=뉴시스 DB겨울 날씨가 이어지면서 미세먼지 주의보가 더욱 잦아 지고 있다. 사실 미세먼지가 어느날 갑자기 나타난 것은 아니다. 미세먼지는 먼 옛날에도 있었지만 측정할 수 있는 장비가 개발된 지 얼마 안됐을 뿐이다. 우리나라는 과거부터 중국에서 날아오는 황사에 고통을 받았다. 그리고 이제는 미세먼지까지 걱정해야 한다.미세먼지는 황사 같은 모래바람과는 달리 화석 연료를 태우는 과정에서 주로 발생한다. 따라서 우리 주위에 있는 자동차, 화력발전소, 가정용 난방 등도 모두 미세먼지의 발생원이 될 수 있다. 특히 최근 중국의 공업화로 중국에서 날아오는 미세먼지의 영향이 점점 커지고 있다. 우리 국민 82.5%가 가장 큰 불안요소 중 하나로 꼽고 있는 미세먼지. 적절한 대비가 필요하다. ◆숨 쉬려면 마셔야 하는 미세먼지우리가 숨을 쉬는 과정에서 먼지 등이 호흡기로 들어오면 코의 털이나 기관지 점막, 세기관지 등을 거치게 된다. 일반적으로 기관지 벽의 점막에 흡착된 뒤 콧물이나 가래에 묻어서 밖으로 배출된다. 그렇지만 미세먼지는 10㎛ 사이즈로 머리카락의 굵기의 약 7분의 1정도밖에 되지 않는다.이런 미세먼지는 기관지를 지나 폐포까지 내려가 더이상 배출되지 않고 그대로 폐에 쌓이게 된다. 문제는 미세먼지에 다양한 환경오염물질인 황산염이나 질산염 등이 묻어 있다는 점이다.이에 따라 체내에 들어간 미세먼지는 폐포 안에서 만성적인 염증을 유발하는데다 지속적으로 장기를 자극, 결국 암으로 진행될 수 있다. 이에 세계보건기구(WHO) 산하 국제암연구소에서는 2013년 미세먼지를 1군 발암물질로 지정했다. 미세먼지는 숨을 쉬는 과정에서 흡입되기 때문에 호흡기에 가장 큰 영향을 미친다. 특히 만성폐쇄성 폐질환이나 천식이 있는 환자의 경우 미세먼지 농도가 높아질수록 급속하게 상태가 나빠지게 된다. 이중에서도 면역력이 떨어지는 소아나 노인층에서는 호흡기 질환이 유발되기도 한다. 소아는 호흡기가 아직 미성

array([[0.        , 0.65607929, 0.94555556, ..., 0.66844178, 0.90044941,
        0.92444381],
       [0.65607929, 0.        , 0.78012124, ..., 0.81948502, 0.90481905,
        0.89852034],
       [0.94555556, 0.78012124, 0.        , ..., 0.94784727, 0.96484795,
        0.91005215],
       ...,
       [0.66844178, 0.81948502, 0.94784727, ..., 0.        , 0.88373135,
        0.89220621],
       [0.90044941, 0.90481905, 0.96484795, ..., 0.88373135, 0.        ,
        0.9605401 ],
       [0.92444381, 0.89852034, 0.91005215, ..., 0.89220621, 0.9605401 ,
        0.        ]])

In [18]:
from sklearn.metrics.pairwise import euclidean_distances
print(euclidean_distances(tfidf_matrix_train[30,:] , tfidf_matrix_train[100,:]))
euclidean_distances(tfidf_matrix_train[30,:] , tfidf_matrix_train)
euclidean_distances(tfidf_matrix_train)

[[29.37686164]]


array([[ 0.        , 48.20788317, 50.11985634, ..., 54.88169094,
        57.45432969, 49.32544982],
       [48.20788317,  0.        , 35.74912586, ..., 53.55371136,
        48.63126566, 37.32291521],
       [50.11985634, 35.74912586,  0.        , ..., 50.21951812,
        41.41255848, 24.67792536],
       ...,
       [54.88169094, 53.55371136, 50.21951812, ...,  0.        ,
        56.98245344, 48.83646179],
       [57.45432969, 48.63126566, 41.41255848, ..., 56.98245344,
         0.        , 40.76763422],
       [49.32544982, 37.32291521, 24.67792536, ..., 48.83646179,
        40.76763422,  0.        ]])

In [19]:
from sklearn.metrics.pairwise import manhattan_distances
manhattan_distances(tfidf_matrix_train[30,:] , tfidf_matrix_train)
manhattan_distances(tfidf_matrix_train)

array([[  0., 530., 468., ..., 624., 567., 471.],
       [530.,   0., 382., ..., 662., 517., 399.],
       [468., 382.,   0., ..., 516., 331., 191.],
       ...,
       [624., 662., 516., ...,   0., 607., 499.],
       [567., 517., 331., ..., 607.,   0., 336.],
       [471., 399., 191., ..., 499., 336.,   0.]])

In [21]:
import numpy as np
from sklearn.metrics import jaccard_score
y_true = np.array([[0, 1, 1],
                    [1, 1, 0]])
y_pred = np.array([[1, 1, 1],
                   [1, 0, 0]])

jaccard_score(y_true[0], y_pred[0])
# jaccard_score(y_true[0,:], y_pred[0,:]) # 위와 같음
jaccard_score(y_true, y_pred, average="samples")
jaccard_score(y_true, y_pred, average=None)

array([0.5, 0.5, 1. ])

바이나리는 숫자가 있는데 0이 아닌 숫자는 1로 0은 그대로 0으로

In [22]:
from sklearn.metrics import jaccard_score
#jaccard_score(tfidf_matrix_train[30,:] , tfidf_matrix_train[31,:])  #error
#jaccard_score(tfidf_matrix_train) #error

tfidf_vect_bin = CountVectorizer(tokenizer=token, min_df=10, binary=True)
bin_matrix = tfidf_vect_bin.fit_transform(train_df['articles'])  #train의 명사를 뽑은 것까지

/usr/local/lib/python3.10/dist-packages/sklearn/feature_extraction/text.py:528: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


In [23]:
bin_array = bin_matrix.toarray()
jaccard_score(bin_array[30,:], bin_array[31,:])

0.06691449814126393

연습 \

제공한 뉴스 시에스븨파일을 가지고 \
DTM: 명사, min_df 0.15, tfidf \
1번 doc, 10번 doc 코사인 유사도, 코사인 거리 \

연습 2 \
제공한 뉴스 시에스븨파일을 가지고 \
DTM: 명사, min_df 0.1, binary \
1번 doc, 10번 doc jaccard score \


In [24]:
import pandas as pd
df = pd.read_csv("news.csv")
df["articles"]

0      게티이미지뱅크 콩나물(사진)은 대두를 발아시켜 뿌리를 자라게 한 것이다. 동의보감에...
1      사진 한 장 없이 떠난 일지 스님 불교 현실에 대한 질타 등 생전에 연재했던 글, ...
2      이재익의 아재음악 열전전태관(왼쪽)과 김종진. <한겨레> 자료사진 2018년을 얼마...
3      서울대병원 제공서울대병원은 올해 1월부터 국내에서 독자적으로 개발한 인공지능 기술을...
4      ㆍ2.1㎓ 속도 ‘엑시노스 오토 V9’ㆍ2021년 생산 차량부터 탑재2021년 생산...
                             ...                        
395    박정호 SK텔레콤 사장이 SK브로드밴드 사장을 겸직한 이후 첫 행보로 ‘옥수수 연합...
396    LG전자가 세계 최초 88인치 8K OLED TV를 내놓는다. 인공지능(AI) 기술...
397    게임은 사회악 아닌 건전한 놀이문화(지디넷코리아=이도원 기자)"게임산업 전체의 발전...
398    10여년 만에 매출예상치 하향…주가도 폭락(지디넷코리아=김익현 기자)최근 10년 여...
399    [머니투데이 판교(경기)=김지영 기자] [최대주주 지분 매각설에 '긴장감' 흘러…게...
Name: articles, Length: 400, dtype: object

In [ ]:
!pip install konlpy

from konlpy.tag import Okt
okt = Okt() #Kkma, Hannanum....
okt.nouns( df["articles"][0] )  #수집된 첫번째 기사에 대한 명사

In [26]:
def token(text):  #함수를 만드는 부분
    tokens_ko = okt.nouns(text) #nouns를 morphs로 바꾸면 명사외에도...
    return tokens_ko

In [27]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

tf_vect = TfidfVectorizer(tokenizer=token,
                          #단어들이 최소 전체의 15% 문서에서 나오는 것만 DTM에 사용
                          min_df=0.15)
dtm = tf_vect.fit_transform( df.articles )
dtm

/usr/local/lib/python3.10/dist-packages/sklearn/feature_extraction/text.py:528: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


<400x199 sparse matrix of type '<class 'numpy.float64'>'
	with 21733 stored elements in Compressed Sparse Row format>

In [ ]:
# ... 계속 ...

위 연습 끝

 - 군집분석: k-means

In [ ]:
from sklearn.cluster import KMeans

km_cluster = KMeans(n_clusters=4)
km_cluster.fit(tfidf_matrix_train)  #DTM을 입력으로 넣음

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


KMeans(n_clusters=4)

In [ ]:
for i in range(3,15):
 print(i, KMeans(n_clusters=i).fit(tfidf_matrix_train).inertia_)

3 257217.58445113554
4 247844.52609427628
5 240057.465232853
6 236070.0880419335
7 223793.33110802868
8 224882.3856731502
9 214066.9680356741
10 214122.9512229234
11 211375.69898785412
12 207539.66172332672
13 205809.12644989142
14 200014.7099374308


In [ ]:
km_cluster.labels_
km_cluster.cluster_centers_[0, :]

array([0.18181818, 0.07575758, 0.02525253, ..., 0.02020202, 0.03030303,
       0.12121212])

In [ ]:
cluster_label = km_cluster.labels_
cluster_label

cluster_centers = km_cluster.cluster_centers_
cluster_centers

print(cluster_centers)
np.argmax( cluster_centers[1,:])  #군집별로 평균 tfidf가 가장 높은 단어를 확인


[[0.18181818 0.07575758 0.02525253 ... 0.02020202 0.03030303 0.12121212]
 [0.30769231 0.11538462 0.         ... 0.73076923 0.19230769 0.07692308]
 [0.         0.36363636 0.54545455 ... 0.09090909 0.09090909 0.45454545]
 [0.84705882 0.07058824 0.         ... 0.         0.04705882 0.23529412]]


63

In [ ]:
print( train_df.iloc[0,2])
print( train_df.iloc[10,2])

[발레인(人) 인터뷰 ③] 1세대 원조 발레 스타의 멈추지 않는 열정, 이원국 발레리노[CBS노컷뉴스 조은정 기자]이원국 발레단의 이원국 단장이 24일 오후 서울 송파구 KBEC발레시어터에서 CBS노컷뉴스와 인터뷰 전 포즈를 취하고 있다. (사진=황진환 기자)이원국 발레리노는 대표적인 1세대 발레 스타이다. '한국 발레리노의 교과서', '발레계의 황태자'로 불리며 화려한 시절을 보냈다. 1967년생, 올해 53살이지만 그는 아직도 현역 무용수로 무대에 오른다. 어려운 여건 속에도 자신의 이름을 딴 이원국발레단을 운영하며 발레 영재들을 키워내고 있다. 수십 년간 단 하루도 발레를 거른 적이 없다는 그에게 발레는 숨쉬는 것처럼 삶 그 자체다. 이원국 발레리노를 크리스마스 이브날 이원국발레단이 있는 서울 송파구 방이동 kbec 발레시어터에서 만났다. 길을 걸으면서도 발레 연습을 한다는 그의 몸은 50대라고 믿기 어려울 정도로 균형잡혀 있었다. 공연에 오르는 횟수만 1년에 100회~150회에 달한다. 근육 만큼이나 발레를 대하는 자세와 마음도 단단했다. 한국 발레의 질적 발전을 위한 쓴소리도 아끼지 않았다. 이원국 발레단의 이원국 단장이 24일 오후 서울 송파구 KBEC발레시어터에서 CBS노컷뉴스와 인터뷰 전 포즈를 취하고 있다. (사진=황진환 기자)▶ 발레를 시작한지 30년이 넘었죠? 이렇게 오래 춤을 출 수 있을거라 생각했나요?1986년 6월1일 부산에서 처음 발레를 접했어요. 32년이 됐네요. 저에게 현역인지 아닌지의 개념은 어느순간 사라졌어요. 그저 '어제도 발레를 했으니 오늘도 할 수 있겠지'라고 생각해요. 발레는 매일매일 새로워요. 30년전 스승님의 가르침을 이제서야 정확하게 깨닫기도 해요. 손가락을 길게 펴라는 것이 이런 거구나, 턴은 이렇게 하는 것이구나. 동작 하나하나의 정확성을 이제야 느끼기도 해요. 물론 잘 안될 때도 있죠. 때로는 좌절을 느끼고 나이가 들어서 그런가 게을러져서 그런가 스스로에게 질문을 하기도 해요. 발레에서 절대적으로 완벽한 사람

In [ ]:
train_df['cluster_label'] = cluster_label
train_df.head()

Unnamed: 0  label                                           articles  \
64           64      0  [발레인(人) 인터뷰 ③] 1세대 원조 발레 스타의 멈추지 않는 열정, 이원국 발레...   
258         258      1  중국 스마트폰 시장 성장 속 미중 무역분쟁에 타격아이폰 차기작 출시시점, 환율, 공...   
226         226      1  김정주 대표. ⓒ 넥슨 김정주 대표, NXC 전량 지분 매각매각 성사되면 국내 최대...   
393         393      1  ㆍ세계 최초 달의 앞·뒷면 모두 밟아‘달의 남극’ 가까이 중국의 달 탐사선 ‘창어 ...   
177         177      0  밴드 봄여름가을겨울의 전태관이 지난 12월 27일 별세했다. /사진=봄여름가을겨울 ...   

     cluster_label  
64               2  
258              0  
226              1  
393              3  
177              2

In [ ]:
# 소속 클러스터를 cluster_label 컬럼으로 할당하고 cluster_label 값으로 정렬
train_df.sort_values(by='cluster_label')

Unnamed: 0  label                                           articles  \
11           11      0  ━ 손민호의 레저터치 세상이 너무 빨리 변한다. 여행·레저 판도 마찬가지다. 이를테...   
134         134      0  -겨울에 많이 발생…냉찜질보다 온찜질을 안구건조증에는 처방받은 안약이나 인공 눈물이...   
185         185      0  [사진=Poznyakov/shutterstock]흥청거리는 연말을 보낸 이라면 찔끔...   
157         157      0  [암 환자는 내 곁에 있다 ④] 암 환자, 치료의 대상 아닌 사회의 일원[사진=im...   
144         144      0  겨울에는 환경적 요인 탓에 안구건조증이 많이 발생한다. 실외에서는 차가운 공기, 바...   
..          ...    ...                                                ...   
271         271      1  2019년 5대 중점 분야 발표...하이브리드 클라우드, 보안, AI, 블록체인 등...   
351         351      1  "플러그인 호환모드, 2018년 10월 중단→2019년까지만 제공"(지디넷코리아=임...   
345         345      1  고객이 롯데하이마트 모바일 매장에서 자급제 스마트폰을 살펴보고 있다. 박지호기자 j...   
368         368      1  이재용 삼성전자 부회장이재용 삼성전자 부회장이 올해 첫 현장경영 행보로 5세대(G)...   
248         248      1  5세대(G) 통신 스마트폰 출시가 가까워지고 있다. 스마트폰업계는 2019년 3월쯤...   

     cluster_label  
11               0  
134              0  
185              0  
157              0  
144              0  
..             ...  
271              3  
351              3  
345              3  
368              3  
248              3  

[320 rows x 4 columns]

In [ ]:
cluster_centers = km_cluster.cluster_centers_
print('cluster_centers shape :',cluster_centers.shape)
print(cluster_centers)

cluster_centers shape : (4, 1430)
[[0.18181818 0.07575758 0.02525253 ... 0.02020202 0.03030303 0.12121212]
 [0.30769231 0.11538462 0.         ... 0.73076923 0.19230769 0.07692308]
 [0.         0.36363636 0.54545455 ... 0.09090909 0.09090909 0.45454545]
 [0.84705882 0.07058824 0.         ... 0.         0.04705882 0.23529412]]


- Hierarchical Clustering

In [ ]:
from sklearn.cluster import AgglomerativeClustering
hclust = AgglomerativeClustering(linkage='ward', n_clusters=10)
#linkage ward, complete, average, 기본값은 ward (ward는 거리가 euclidean에서 가능)
hclust.fit(np.asarray(tfidf_matrix_train.todense()))
hclust.labels_	#각 자료에 대한 클러스터 결과

array([1, 2, 4, 7, 1, 4, 3, 4, 3, 3, 3, 3, 3, 2, 3, 3, 4, 3, 2, 4, 4, 3,
       3, 3, 3, 2, 3, 3, 3, 2, 3, 3, 3, 3, 2, 3, 2, 1, 3, 3, 2, 3, 3, 2,
       2, 3, 3, 1, 3, 2, 3, 3, 3, 3, 3, 2, 2, 7, 3, 3, 3, 3, 3, 2, 3, 3,
       2, 2, 7, 6, 2, 6, 4, 3, 2, 3, 3, 3, 6, 3, 2, 2, 4, 3, 2, 3, 3, 2,
       2, 3, 4, 2, 3, 7, 3, 2, 3, 3, 3, 4, 3, 3, 3, 3, 3, 3, 3, 4, 3, 3,
       1, 3, 4, 1, 2, 1, 3, 3, 2, 3, 3, 3, 3, 2, 3, 2, 3, 3, 7, 3, 5, 3,
       3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 2, 4, 4, 3, 7, 2, 2, 3, 3, 2, 2, 2,
       1, 3, 2, 2, 3, 0, 1, 2, 4, 8, 3, 3, 8, 2, 3, 3, 2, 4, 4, 3, 4, 3,
       4, 3, 3, 3, 2, 3, 2, 4, 2, 2, 4, 4, 6, 3, 8, 2, 3, 3, 3, 3, 3, 2,
       2, 3, 3, 3, 2, 7, 3, 3, 0, 4, 6, 3, 3, 3, 2, 1, 8, 3, 6, 2, 3, 2,
       6, 3, 3, 1, 3, 3, 3, 3, 3, 2, 4, 2, 1, 3, 3, 8, 2, 3, 2, 3, 3, 3,
       3, 5, 3, 3, 3, 3, 3, 3, 2, 4, 3, 3, 2, 3, 5, 3, 2, 1, 2, 7, 3, 2,
       3, 3, 2, 4, 2, 3, 3, 2, 4, 2, 3, 2, 3, 6, 2, 3, 9, 3, 3, 8, 6, 3,
       7, 2, 2, 4, 3, 3, 3, 3, 3, 2, 8, 3, 3, 2, 3,